type: com.google.api.codegen.ConfigProto
config_schema_version: 2.0.0
# The settings of generated code in a specific language.
language_settings:
  java:
    package_name: com.google.cloud.tasks.v2beta3
  python:
    package_name: google.cloud.tasks_v2beta3.gapic
  go:
    package_name: cloud.google.com/go/cloudtasks/apiv2beta3
  csharp:
    package_name: Google.Cloud.Tasks.V2Beta3
  ruby:
    package_name: Google::Cloud::Tasks::V2beta3
  php:
    package_name: Google\Cloud\Tasks\V2beta3
  nodejs:
    package_name: tasks.v2beta3
interfaces:
- name: google.cloud.tasks.v2beta3.CloudTasks
  methods:
  - name: ListQueues
    timeout_millis: 10000
  - name: GetQueue
    timeout_millis: 10000
  - name: CreateQueue
    timeout_millis: 10000
  - name: UpdateQueue
    timeout_millis: 10000
  - name: DeleteQueue
    retry_codes_name: idempotent
    retry_params_name: default
    timeout_millis: 10000
  - name: PurgeQueue
    timeout_millis: 10000
  - name: PauseQueue
    timeout_millis: 10000
  - name: ResumeQueue
    timeout_millis: 10000
  - name: GetIamPolicy
    timeout_millis: 10000
  - name: SetIamPolicy
    timeout_millis: 10000
  - name: TestIamPermissions
    timeout_millis: 10000
  - name: ListTasks
    timeout_millis: 10000
  - name: GetTask
    timeout_millis: 10000
  - name: CreateTask
    timeout_millis: 10000
  - name: DeleteTask
    timeout_millis: 10000
  - name: RunTask
    timeout_millis: 10000
